### ISSUE TITLE
`start_eye_plugin` notification is not received if backend is started before Capture

### ISSUE THREAD

**Issue by papr** [Lifestohack/pupil-video-backend#1]
With this start sequence, Pupil Remote relays the notification before the eye process is launched and it gets lost without being handled.

**Comment by Lifestohack** [comment]
Reproduction steps:

1. Start pupil capture software. 
2. Click on "Detect eye 0" on pupil capture software. Small window pops up where eye0 video feed supposed to be shown. 
3. Started pupil video backend. 

But pupil detection eye 0 window closes automatically. And pupil capture shows the error: Process Eye0 crashed with trace.

```
2020-11-12 13:32:15,630 - world - [DEBUG] network_api.controller.pupil_remote_controller: Request: 'PUB_PORT', Response: '44017'
2020-11-12 13:32:15,634 - world - [DEBUG] network_api.controller.pupil_remote_controller: Request: 'notify.start_eye_plugin', Response: 'Message forwarded.'
2020-11-12 13:32:15,656 - eye0 - [DEBUG] plugin: Replacing Video Source due to 'by_base_class' uniqueness
2020-11-12 13:32:15,656 - eye0 - [DEBUG] plugin: Unloaded Plugin: <video_capture.uvc_backend.UVC_Source object at 0x7f0e638784a8>
2020-11-12 13:32:15,657 - eye0 - [ERROR] launchables.eye: Process Eye0 crashed with trace:
Traceback (most recent call last):
  File "launchables/eye.py", line 654, in eye
  File "shared_modules/plugin.py", line 398, in add
  File "shared_modules/video_capture/hmd_streaming.py", line 50, in __init__
AttributeError: 'types.SimpleNamespace' object has no attribute 'zmq_ctx'
```

**Comment by papr** [comment]
@Lifestohack This issue assumes the opposite sequence. The issue you encountered is a duplicate of https://github.com/pupil-labs/pupil/issues/2049

**Comment by Lifestohack** [comment]
This issue and pupil-labs/pupil#2049 are two different issues? What do you mean by opposite sequence?

**Comment by papr** [comment]
Yes, #1 and pupil-labs/pupil#2049 two separate issues. #1 is about the following sequence:
1. Backend started, waits for Capture
2. Start Capture
3. World process launches, backend connects to Pupil Remote
4. Backend sends start_eye_plugin notification
5. Pupil Remote receives notifications and relays
6. Nobody handles notification
7. Eye process launches (due to some defined delay)
8. `HMD_Streaming_Source` is not started in eye process

**Comment by Lifestohack** [comment]
needs to check if eye process has started or not and if not then need to notify again. I see following notification that is being emitted:

```
    Emits notifications:
        ``eye_process.started``: Eye process started
        ``eye_process.stopped``: Eye process stopped
```
Needs to check if   this is true -> ``eye_process.started``: Eye process started
is this the notification to check if eye process has started?
`{"subject": "eye_process.started", "eye_id": eye0}`

**Comment by Lifestohack** [comment]
With {"subject": "eye_process.should_start.0", "eye_id": 0, "args": {}} I can start the eye process.

**Comment by papr** [comment]
@Lifestohack The eye process will be started by Capture already. You basically need to send `start_eye_plugin` once in the beginning and every time the `eye_process.started` notification is being announced. Subscribe to `notify.eye_process.started` to receive it on your end.

**Comment by Lifestohack** [comment]
@papr I Subscribed to the notification. If world view is started then it directly starts streaming. If eye_process is started in pupil capture software then it starts streaming and if eye_process is stopped then it also stops streaming. If Pupil capture software is closed then it stops streaming and asks for PUB_PORT again.

**Comment by Lifestohack** [comment]
commit 2852950 has fixed this issue. Closing.
