### ISSUE TITLE
Camera Choice

### ISSUE THREAD

**Issue by souravrs999** [Lifestohack/pupil-video-backend#4]
Will this work with any normal camera like a rasberry camera module or do we still have to use those recommended by pupil labs like Logitech c525

Thanks in advance

**Comment by Lifestohack** [comment]
This will work with any camera. Please look at the example folder for raspberry pi camera module example. This way you will not be able to control the brightness or any other settings from the pupil capture software. You need to write on your code to control those settings if necessary on the server side.

**Comment by souravrs999** [comment]
> This will work with any camera. Please look at the example folder for raspberry pi camera module example. This way you will not be able to control the brightness or any other settings from the pupil capture software. You need to write on your code to control those settings if necessary on the server side.

I tried to run with the built in camera of my laptop but ran into an error 

`AttributeError: 'types.SimpleNamespace' object has no attribute 'zmq_ctx'`

i think it might be due to some version mismatch also can we use this with precompiled debian packages

Thanks for the quick answer

**Comment by Lifestohack** [comment]
is that error from capture.log on pupil capture software? I think you are running old version of the software. This bug was fixed on version 2.6. The error was fixed here. https://github.com/pupil-labs/pupil/issues/2049
Please download the version 2.6 of pupil capture software from here: https://github.com/pupil-labs/pupil/releases/tag/v2.6#user-content-downloads

**Comment by souravrs999** [comment]
> is that error from capture.log on pupil capture software? I think you are running old version of the software. This bug was fixed on version 2.6. The error was fixed here. [pupil-labs/pupil#2049](https://github.com/pupil-labs/pupil/issues/2049)
> Please download the version 2.6 of pupil capture software from here: https://github.com/pupil-labs/pupil/releases/tag/v2.6#user-content-downloads

Yes that error was from the Pupil Capture software
oh just noticed that i'm running v2.5
also do you think this particular cam will work
[Mini ir camera](https://www.amazon.in/Honelife-Camera-Vision-Extended-Memory/dp/B08NFTCKTH/ref=sr_1_5?dchild=1&keywords=mini+ir+camera&qid=1605968137&sr=8-5)

Thanks a lot by the way for quick answers and proper explanations hard to find those nowadays

**Comment by Lifestohack** [comment]
Normally If you can interface it with usb or wireless on your local or remote computer then you can use this program to relay the videos to your pupil capture software. This software just provides bare minimum implementation using opencv. But if you want to use your own devices and if opencv videocapture function could not interface with your devices then you have to write your own program to read the frames of your camera.

**Comment by souravrs999** [comment]
> Normally If you can interface it with usb or wireless on your local or remote computer then you can use this program to relay the videos to your pupil capture software. This software just provides bare minimum implementation using opencv. But if you want to use your own devices and if opencv videocapture function could not interface with your devices then you have to write your own program to read the frames of your camera.

Do you know why pupil capture only work with Logitech and microsoft cameras and crash on others

**Comment by Lifestohack** [comment]
I am not the developer for pupil capture software and has nothing to do with that company. But what I see on their source code is, it has to do with UVC standards. Not every camera follows this standard. Pupil capture software filters out the USB cameras that are not UVC compliments.
https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/video_capture/uvc_backend.py

**Comment by souravrs999** [comment]
> I am not the developer for pupil capture software and has nothing to do with that company. But what I see on their source code is, it has to do with UVC standards. Not every camera follows this standard. Pupil capture software filters out the USB cameras that are not UVC compliments.
> https://github.com/pupil-labs/pupil/blob/master/pupil_src/shared_modules/video_capture/uvc_backend.py

Tnx for the help and that does make sense
